### PR TITLE
Remove Rainbow, avoid race in creating directories

### PR DESCRIPTION
**Pull request by quozl**
Sugar depended on Rainbow for clearing the activity instance/ and tmp/ directories.  But Rainbow is no longer used downstream.

 - remove support for Rainbow,

 - avoid race when creating directories; don't check they exist before we create.

### CODE REVIEW

**Comment by samdroid-apps** [comment]
This patch is a NAK from my perspective.

As @godiard said on the mailing list, what if the user has 2 activity instances open?  When you close the first instance, it will clear it's instance dir and leave it in a bad state.  Please clear it at a different time to address that issue.

Otherwise it looks like a good patch.

**Comment by quozl** [comment]
Any reason why not say this on mailing list where the discussion is?

**Comment by quozl** [comment]
Ping?  Substantial change to patch, please review.

**Comment by samdroid-apps** [comment]
From Gonzalo's reply to your initial mailing list post:

> A few issues:
> ...
> * Temporary directories are shared between instances, if we remove temporary directories 
at activity start or stop, we need check if there are other instances of the activity running.

Please address this.  Currently, your patch description says it will delete files from under the activity's eyes if a 2nd instance is launched.

Also, where is the code that actually removes the directories?

**Comment by quozl** [comment]
> Currently, your patch description says it will delete files

No, it doesn't.  Look at the commit carefully?

**Comment by samdroid-apps** [comment]
Ah, I see.  I just edited the initial pull request comment to reflect the new commit message.

This looks fine to me.  I'll just test 'n' merge.

**Pull request merged**
