### PR TITLE
Use SVG metadata for icon badge attachment points

### PR DESCRIPTION
**Pull request by SAMdroid-apps**
Replaces #198

> `gtk_icon_info_get_attach_points` has been deprecated since version 3.14 and should not be used in newly-written code.
>
> Attachment points are deprecated

From https://developer.gnome.org/gtk3/stable/GtkIconTheme.html#gtk-icon-info-get-attach-points

This commit uses the new `sugar:attach-point` metadata to get the attachment
point.  GTK has returned (0, 0) since version 3.14, meaning that the network
view WiFi icons (just as an example) have looked a little bit off.

### CODE REVIEW

**Comment by SAMdroid-apps** [comment]
Requires https://github.com/sugarlabs/sugar-artwork/pull/45 for the SVGs

**Comment by quozl** [comment]
Tested.  Breaks display of WiFi icons on Fedora 18 with Sugar 0.104.  Screenshot: captura pantalla de _malla_

**Comment by SAMdroid-apps** [comment]
Did you update the icon theme?  Can you double check the icon changes flowed through (I had major issues getting the icon changes reflected)?

**Comment by quozl** [comment]
Ok, no, I missed that.  I'll try again tomorrow, hopefully.

**Comment by godiard** [comment]
HI @SAMdroid-apps , @quozl, i have pushed a alternative solution for this problem (https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/200) where we don't need modify the artwork.
I think would be better keep the information for the attach points separated from the svg.
What you think? Can you test and compare?

**Comment by SAMdroid-apps** [comment]
I find having a whole file for 1 little piece of metadata a little weird (personally).

**Comment by SAMdroid-apps** [comment]
@quozl, can you test this with the icons?

**Comment by quozl** [comment]
@godiard, i've no issue with either method of coding the metadata.
@SAMdroid-apps, i've not had time, testing of icon.py file change was a mv, wget, and restart.  testing of icons looks a whole lot harder.  do you have a test method?

**Comment by godiard** [comment]
We merged the alternative solution.

**Pull request closed without merging**
