### PR TITLE
Port to Six { Ongoing }

### PR DESCRIPTION
**Pull request by octamois**
Progress goals under evaluation for #382 :

- [ ] fix a critical accidental dependency; remove the from jarabe.model import shell from src/sugar3/graphics/popwindow.py and use some other design,
- [ ] port toolkit code in src/sugar3 which calls C code, and test that the C code can be called from REPL,
- [ ] port toolkit code in src/sugar3/graphics,
- [x] port graphics examples
- [x] examples are tested
- [x] Include old files with .bak for **Backup**
- [ ]  port toolkit code in src/sugar3/activity,
- [ ] regenerate documentation,
- [ ]  port make files, and test that "make install" installs both bindings,
- [ ] make local Fedora and Debian packages for testing by others.

### CODE REVIEW

**Comment by quozl** [comment]
https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/383 has already ported some of these files; I don't know how your changes fit together with those ones.

Were the tests run with python3?  If not, you'll need other changes from #383.

Don't make .bak files, they make it impractical to review the changes in a pull request, and the old files are always available in git.

**Comment by Pro-Panda** [comment]
@octamois, the changes in this PR seem repititive
#383 already has the changes, and are tested with Python3.

**Comment by quozl** [comment]
See my comment in issue https://github.com/sugarlabs/sugar-toolkit-gtk3/issues/382.

**Comment by octamois** [comment]
@quozl noted
I saw that #383 was not merged, I will follow the prescribed method to avoid redundancy in upcoming stages.

**Pull request closed without merging**
