### PR TITLE
Write docs for sugar3.graphics.style

### PR DESCRIPTION
**Pull request by ndefilippis**
I made a new branch, and this one should have correct indentation

### CODE REVIEW

**Comment by ndefilippis** [comment]
For future reference, how do I add the doc label?

**Comment by quozl** [comment]
The feature to add the labels only appeared for me when I was added as a group member of sugarlabs organisation in github.

**Comment by ndefilippis** [comment]
Oh ok, the guide said to add the doc label, but if I can't do it myself, that's fine

**Comment by quozl** [comment]
What guide?

**Comment by ndefilippis** [comment]
http://wiki.sugarlabs.org/go/Features/Sugar3Docs/HowToWrite. It was linked in the Google Code-In task information

**Comment by quozl** [comment]
I'm not part of GCI, sorry.  I've edited the Wiki page, it was wrong in that respect.

**Comment by samdroid-apps** [comment]
Hum, I went and built this and it did not come out with the constants listed.  If you need help setting up sphinx, please ask.

Anyway, I found that you can get it to show the constants if you put `#:` or `#: Description` at the end of their line.  Maybe you could look into this?  Or maybe that would be tooo ugly!

**Comment by ndefilippis** [comment]
Does that mean that the constants don't need documentation, or I didn't document them correctly? Also, with sphinx, any help would be greatly appreciated

**Comment by quozl** [comment]
Reviewed.

**Pull request merged**
