### PR TITLE
drop Python 2.3 fallback

### PR DESCRIPTION
**Pull request by a-detiste**

### CODE REVIEW

**Comment by walterbender** [comment]
This probably makes sense, but there is no associated ticket or explanation for this change.

**Comment by a-detiste** [comment]
Hi, I'm just testing the waters to see if Python2 support can be wholefully removed.

Asking for a ticket means I know I won't try to get further.

https://wiki.debian.org/Python3-six-removal

**Comment by a-detiste** [comment]
Sorry I think I'm being abrupt here assuming unsaid thing :-|

**Comment by chimosky** [comment]
> Sorry I think I'm being abrupt here assuming unsaid thing :-|

It's totally okay, I do agree with the change.

**Comment by chimosky** [comment]
Merged by hand, thank you!

**Pull request closed without merging**
