### PR TITLE
Fix deprecations

### LINKED ISSUE #405: Build warnings from gcc
gcc has changed and the toolkit has not, and so there are several warnings issued by the compiler.

* [ ] capture the warnings by using `make`,
* [ ] fix warnings,
* [ ] confirm the warnings are removed.

Requires gcc compiler experience or learning.

Build log from Fedora: 
[build.log](https://github.com/sugarlabs/sugar-toolkit-gtk3/files/3086886/build.log)

Build log from Ubuntu 16.04:
[build.log](http://dev.laptop.org/~quozl/z/1i50IL.txt)

### PR DESCRIPTION
**Pull request by chimosky**
Fixes #405

@quozl @aperezbios kindly review.

### CODE REVIEW

**Comment by quozl** [comment]
Looked at the changes, but didn't really validate them.  Do tests work?

**Comment by chimosky** [comment]
Yeah, I did test some events like touch and zoom and they worked fine. 

Tested touch on the home view.

**Comment by chimosky** [comment]
@quozl can you test and review this?

**Comment by quozl** [comment]
Sorry, not really in a position to do that level of testing.  The changes look fine, and if you've tested them (build, install, run), let's get this merged, and rely on any bug reports.

**Comment by chimosky** [comment]
Yes, I did test this.

**Pull request merged**
