### PR TITLE
Get audio and video mimes from GStreamer, fixes #3826

### PR DESCRIPTION
**Pull request by SAMdroid-apps**
Now with caching!

Replaces #187

GCI Ticket:  http://www.google-melange.com/gci/task/view/google/gci2014/5810064153640960

### CODE REVIEW

**Comment by quozl** [comment]
Martin, because only the FS is persistent.

This is adequate, since first boot is allowed to be slower.  But to avoid slower first boot, the change might instead be added to the install phase of setup.py.  Effectively it would be configuring the Sugar environment for the GStreamer environment found, without having to incur the cost of reading that environment on every boot.

**Comment by godiard** [comment]
I am testing this. 
There are any reason to change the structure to store the mimetypes from one array to a set?
This break the compatibility and by example breaks the Journal, when want filter by image or video, you can see a error in the log, and nothing is filtered:
```
1420663593.230210 ERROR dbus.connection: Unable to set arguments ({'mountpoints': ['/'], 'order_by': ['+timestamp'], 'mime_type': set(['application/x-gst-av-vmd', 'application/ogg', 'application/x-gst-av-wc3movie', 'audio/x-mulaw', 'audio/x-speex', 'audio/webm', 'application/x-gst-av-nuv', 'application/x-icy', 'application/x-3gp', 'application/x-gst-av-wsvqa', 'audio/x-m4a', 'audio/x-private-ts-lpcm', 'application/x-gst-av-avs', 'application/x-gst-av-ipmovie', 'audio/x-avi-unknown', 'application/x-gst-av-mm', 'audio/AMR-WB', 'audio/x-lpcm', 'application/x-ass', 'audio/ms-gsm', 'application/x-hls', 'application/x-usf', 'audio/x-adpcm', 'audio/x-eac3', 'audio/x-truespeech', 'application/kate', 'application/x-rtp', 'audio/x-musepack', 'application/x-gst-av-ea', 'audio/x-alaw', 'audio/subtitles', 'application/x-apetag', 'audio/x-nellymoser', 'audio/AMR', 'audio/x-voxware', 'application/x-yuv4mpeg', 'application/x-gst-av-wsaud', 'application/x-gst-av-daud', 'application/x-pn-realaudio', 'application/x-gst-av-mmf', 'audio/x-dts', 'audio/x-wav', 'audio/x-matroska', 'application/x-ssa', 'audio/x-ac3', 'application/sdp', 'audio/mpeg', 'application/gxf', 'audio/x-private1-lpcm', 'audio/x-aiff', 'audio/x-private1-ac3', 'application/x-gst-av-nut', 'audio/x-siren', 'audio/x-au', 'audio/x-private1-dts', 'audio/ac3', 'audio/x-wms', 'application/x-gst-av-psxstr', 'audio/ogg', 'application/x-rtcp', 'audio/x-vorbis', 'audio/x-raw', 'application/x-gst-av-sol', 'application/x-gst-av-idcin', 'application/x-ogg-avi', 'audio/x-ttafile', 'audio/x-voc', 'application/x-gst-av-ffm', 'application/x-ape', 'audio/x-wma', 'application/mxf', 'application/x-id3', 'application/x-gst-av-smk'])},) according to signature u'a{sv}': <type 'exceptions.TypeError'>: Don't know which D-Bus type to use to encode type "set"
Traceback (most recent call last):
  File "/home/gonzalo/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/journal/journalactivity.py", line 273, in _query_changed_cb
    self._list_view.update_with_query(query)
  File "/home/gonzalo/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/journal/listview.py", line 334, in update_with_query
    self.refresh(new_query=True)
  File "/home/gonzalo/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/journal/listview.py", line 351, in refresh
    self._model.setup()
  File "/home/gonzalo/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/journal/listmodel.py", line 111, in setup
    self._result_set.setup()
  File "/home/gonzalo/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/journal/model.py", line 104, in setup
    self.ready.send(self)
  File "/home/gonzalo/sugar-build/build/out/install/lib/python2.7/site-packages/sugar3/dispatch/dispatcher.py", line 130, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/gonzalo/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/journal/listmodel.py", line 103, in __result_set_ready_cb
    self._all_ids = self._result_set.find_ids(self._query)
  File "/home/gonzalo/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/journal/model.py", line 234, in find_ids
    return _get_datastore().find_ids(query)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: Don't know which D-Bus type to use to encode type "set"

```

**Comment by SAMdroid-apps** [comment]
@quozl, I could definitly move it to setup.py but 2 things:

1) I think I need to keep the mime.py code as is.  If somebody installs new mimes, they may want to delete the cache, so it needs to be regenerated if that heppens
2) Where is this setup.py? :smile:

@godiard, didn't find that!  I will fix that!  I just had them as a set so there isn't any duplication, but I will convert them to a list.

**Comment by godiard** [comment]
I think create the cache in the first use is ok, we don't need add this to the first sugar startup.

**Comment by SAMdroid-apps** [comment]
@godiard yeah, but if the user deletes the cache, we need to remake it?

**Comment by godiard** [comment]
@SAMdroid-apps, sure. If the file does not exist is created.

**Comment by quozl** [comment]
And first use might be by Journal, not startup?

**Comment by godiard** [comment]
@quozl, the first time the journal (or one activity) filter by video or audio, if I am not wrong.

**Comment by SAMdroid-apps** [comment]
@godiard So you want it to generate on first use?

**Comment by godiard** [comment]
@SAMdroid-apps, yes. Anybody have a reason to not do it?

**Comment by SAMdroid-apps** [comment]
Okie dokie @godiard

**Comment by quozl** [comment]
I agree.  Also, since much of the work is being done in subprocesses (one followed by many), you can run those asynchronously and handle the output as it arrives, without blocking the UI.  An input add, rather than an idle add, though it could be done with idle add if you check for readability of the process pipe before reading it.

Really a pity all this discussion gets lost in each pull request when it should really go on the ticket.  ;-)

**Pull request closed without merging**
