### PR TITLE
Added documentation and example for progressicon

### PR DESCRIPTION
**Pull request by Hrishi1999**
I've documented progressicon.py and created example. 
From my previous work : https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/299
My previous work didn't include an example. I've added it now.

### CODE REVIEW

**Comment by quozl** [comment]
You've started badly; there are two commits instead of one, and your
commit message don't comply with our guide to contributing or the
previous pull-request on documentation.

I've not looked at your commits in detail yet.

**Comment by Hrishi1999** [comment]
@quozl, you can review it.

**Comment by Hrishi1999** [comment]
I will fix commit message.

**Comment by Hrishi1999** [comment]
Yes, @walterbender asked me to update it. Please review it.

**Comment by quozl** [comment]
Thanks.  Tested the example.  It was okay.  Reviewed commits;

- [ ] `Parameters` should be `Keyword arguments` or just `Args`; to comply with style, see [Wiki Sugar3 Docs](https://wiki.sugarlabs.org/go/Features/Sugar3_Docs);
- [ ] there is no `COLOR_BUTTON_RED`; use an explicit colour instead, or do not give an example; and,
- [ ] missing space after `e.g.` and before `stroke_color`.

@iamutkarshtiwari, since you wrote `progressicon.py` do you have any comments on this pull request?

@Hrishi1999, your branch `patch-1` is based on (old) 53c5058da08c11f167087a34d7dc7344d2b86098 instead of (new) 67120db59343fcc5b61843327abea9fddafe2381.  Please merge with upstream master.  See [Keep your fork up to date](https://developer.sugarlabs.org/contributing.md.html).

**Comment by quozl** [comment]
Hopefully you are also using `make-doc.sh` and `python -m SimpleHTTPServer` to review how your documentation changes appear in context.  Here's what your branch looks like as of c57ff0e.

screenshot of _browse activity_

Additional comments;
- [ ] `do_get_preferred_*` methods are listed but not documented,
- [ ] the sugar3.graphics.icon.Icon text is not a link,
- [ ] the Gtk.DrawingArea text is not a link,
- [ ] some of the keyword arguments start with a bullet point then a "-",
- [ ] *The progressicon module* is redundant in context, since the heading immediately above (not in the screenshot) is *sugar3.graphics.progressicon module*,

**Comment by quozl** [comment]
`Parameters` is acceptable, per [Napoleon](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/) list of Docstring Sections which shows `Args` is an alias.

**Comment by Hrishi1999** [comment]
@quozl Done :D

**Comment by quozl** [comment]
Continuing to wait.

Checkboxes in previous comments above have been updated.

99130b02639600f2645667eb514ef0eea4df0fa5 is a recent commit that shows how to make a clickable reference to sugar3.graphics.icon.Icon

**Comment by Hrishi1999** [comment]
@quozl. I don't see check boxes updated. What is the problem exactly?

**Comment by Hrishi1999** [comment]
Checking again  i found that I have considered pixel_size as string and not integer. I will fix that. But what links you were talking about and what about make-docs.sh

**Comment by Hrishi1999** [comment]
@quozl, review this. And did you use make-doc .sh in sugar devenv. I am having issues installing Sphinx.

**Comment by quozl** [comment]
Thanks, I had already reviewed 9203025, but was waiting for you to respond my other checkboxes in the pull-request; that are not yet checked-off or ticked.  If you have some problem with them, let me know.  I have checked with other people and they can see the checkboxes.

- [ ] this is what a checkbox looks like.

Yes, I used `make-doc.sh`, but not inside `sugar-build`.  I don't use or recommend `sugar-build`, but I don't see why it should not work.  You will need to install Sphinx to be able to use `make-doc.sh`.  I used Ubuntu 16.04 and this step;
```
apt install python-sphinx
```

Hope that helps.

**Comment by Hrishi1999** [comment]
Thanks. I know what is a checkbox (I am a dev, I've made apps, (not in python)). Let me use Ubuntu and wait.

**Comment by Hrishi1999** [comment]
https://paste.fedoraproject.org/519205/
This is what happens.

**Comment by quozl** [comment]
I've seen that here.  `trusty` is Ubuntu 14.04, and the `python-sphinx` package in that release does not load a compatible version of `napoleon`.  That's why I said Ubuntu 16.04.

**Comment by Hrishi1999** [comment]
@quozl https://paste.fedoraproject.org/519205/

**Comment by Hrishi1999** [comment]
"there is no COLOR_BUTTON_RED; use an explicit colour instead, or do not give an example; and,"
And I've removed the example.

**Pull request closed without merging**
