### PR TITLE
use xml.etree.ElementTree as xml.etree.CElementTree will be deprecated

### PR DESCRIPTION
**Pull request by chimosky**
This is a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1817644 

@nullr0ute @aperezbios 

@quozl kindly review.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.

https://bugzilla.redhat.com/show_bug.cgi is a bad link?

On Python 3 we get _ModuleNotFoundError_ not _ImportError_.  Is the exception handler properly constructed to be both Python 2 and Python 3 compatible?

Can't we just replace the import with `import xml.etree.ElementTree as ET`?

**Comment by chimosky** [comment]
> https://bugzilla.redhat.com/show_bug.cgi is a bad link?

Yeah, replaced that in my opening comment.

> On Python 3 we get ModuleNotFoundError not ImportError. Is the exception handler properly constructed to be both Python 2 and Python 3 compatible?

Yeah, my bad. 

> Can't we just replace the import with import `xml.etree.ElementTree as ET`?

Yes we can just do that, I added the exception for convenience. 
I'll just import `xml.etree.Elementree as ET`.

**Comment by quozl** [comment]
8c976bd56a488d5612b1f69b24c45af114219079

**Comment by encukou** [comment]
> On Python 3 we get ModuleNotFoundError not ImportError. 

FWIW, ModuleNotFoundError is a subclass of ImportError, so `except ImportError` would handle both.

**Comment by chimosky** [comment]
> > On Python 3 we get ModuleNotFoundError not ImportError.
> 
> FWIW, ModuleNotFoundError is a subclass of ImportError, so `except ImportError` would handle both.

Yeah it should but for some reason, `isinstance(ModuleNotFoundError, ImportError)` returns `False`.

**Comment by encukou** [comment]
You want `issubclass` for classes.
```pycon
>>> issubclass(ModuleNotFoundError, ImportError)
True
>>> isinstance(ModuleNotFoundError(), ImportError)  # note extra parentheses
True
>>> try:
...     raise ModuleNotFoundError
... except ImportError:
...     print('handled')
... 
handled
```

**Comment by chimosky** [comment]
> You want `issubclass` for classes.
> 
> ```
> >>> issubclass(ModuleNotFoundError, ImportError)
> True
> >>> isinstance(ModuleNotFoundError(), ImportError)  # note extra parentheses
> True
> >>> try:
> ...     raise ModuleNotFoundError
> ... except ImportError:
> ...     print('handled')
> ... 
> handled
> ```

Thanks

**Pull request closed without merging**
