### PR TITLE
Write documentation for sugar3.graphics.style

### PR DESCRIPTION
**Pull request by ndefilippis**
I just reforked and repulled becaues I couldn't figure out rebase

### CODE REVIEW

**Comment by quozl** [comment]
Sorry, but your commit contains git conflict markers, please try again and check your commit carefully before sending pull request.

**Comment by quozl** [comment]
Perhaps you might ask for help on rebasing in the previous pull request?  I'm happy to help there or on IRC.

**Comment by ndefilippis** [comment]
What are conflict markers?

**Comment by quozl** [comment]
Conflict markers are inserted by git during a merge, and you are expected to resolve them, edit them out, and complete the commit.  When you've left them in a commit it means you didn't finish resolving 
before commit.

**Comment by quozl** [comment]
Also, you might like to know that you can do a rebase and then force push onto your original pull request.  It takes a few careful steps, but it keeps the history of comments in one place.  Some of us like that.  :grin:

**Pull request closed without merging**
