### PR TITLE
Write documentation for sugar3.graphics.combobox

### PR DESCRIPTION
**Pull request by samdroid-apps**

### CODE REVIEW

**Comment by samdroid-apps** [comment]
Eventually I'll upload the docs and give them a nice place, but you can view it here if you want:

http://people.sugarlabs.org/sam/sugar3.graphics.combobox.html

**Comment by samdroid-apps** [comment]
This is just a documentation addition.  Can I merge this myself?

**Comment by godiard** [comment]
+1

**Comment by quozl** [comment]
Reviewed.  I confirm no functional change, so go ahead.

**Pull request merged**
