### PR TITLE
flake8 fixes

### PR DESCRIPTION
**Pull request by Aniket21mathur**

### CODE REVIEW

**Comment by quozl** [comment]
Briefly reviewed;
* doc/conf.py is an upstream file, and changing it creates unnecessary difference, so please exclude it from flake8 and changes,
* the appstream metadata for screenshots might not be capable of being split in that fashion, please explain how you tested this,
* line 1381 of icon.py loses whitespace that is correct english usage.

**Comment by Aniket21mathur** [comment]
>     * doc/conf.py is an upstream file, and changing it creates unnecessary difference, so please exclude it from flake8 and changes

Changed.

>     * the appstream metadata for screenshots might not be capable of being split in that fashion, please explain how you tested this,

I reverted the changes. Thanks for pointing out.

>     * line 1381 of icon.py loses whitespace that is correct english usage.

Thanks. Fixed!

**Comment by quozl** [comment]
Thanks.  Tested with flake8 on Python 2 and Python 3; these remain;

```log
./tests/test_lru.py:6:12: E999 SyntaxError: invalid syntax
./src/sugar3/logger.py:195:23: F821 undefined name 'long'
./src/sugar3/bundle/__init__.py:161:80: E501 line too long (137 > 79 characters)
./src/sugar3/activity/activityinstance.py:25:5: F821 undefined name 'reload'
```

and doc/conf.py is not excluded.

**Comment by Aniket21mathur** [comment]
> ./src/sugar3/bundle/__init__.py:161:80: E501 line too long (137 > 79 characters)

Because of Appstream metadeta of screenshots.

> ./src/sugar3/logger.py:195:23: F821 undefined name 'long'

Use of `six` introduced it, please see

```
if six.PY2:
        _TYPES.append(long)
```


> ./src/sugar3/activity/activityinstance.py:25:5: F821 undefined name 'reload'

Again resulted from use of `six`.


> ./tests/test_lru.py:6:12: E999 SyntaxError: invalid syntax

Sorry, but I am not able to find any such file in the toolkit, nor does it exist on github, as I have check now.



>  doc/conf.py is not excluded.

Reviewed the changes again, sorry I am not able to find any changes in it.

Thanks!

**Comment by quozl** [comment]
Thanks for checking.  test_lru.py was a local file in my repository.  doc/conf.py ought to be excluded by .flake8 somehow, but it can be done later.

**Pull request merged**
