### PR TITLE
Remove unwanted dependency of toolkit to jarabe

### PR DESCRIPTION
**Pull request by pro-panda**
- Add exmaple demonstrating `sugar3.graphics.popwindow.PopWindow`
 - Remove dependancy of `sugar3.graohics.popwindow` to `jarabe`

### CODE REVIEW

**Comment by Pro-Panda** [comment]
Tested on Ubuntu 16.04, Sugar 0.112

**Comment by Pro-Panda** [comment]
I couldn't find what to fix in `sugar:src/jarabe/desktop/activitychooser.py`.

Didn't understand 'window remains modal' :sweat_smile:

**Comment by Pro-Panda** [comment]
Sorry, but I don't think this change removed the Modal behaviour. I think I misunderstood

**Comment by quozl** [comment]
I'll explain further.

When the Journal project feature was added, one of the new dialogs was an activity chooser; which displays a list of activities.  As most dialogs in Sugar are modal, so was this new dialog.  Part of the implementation of this dialog was placed in the `sugar-toolkit-gtk3` module `sugar3/graphics`, and part in the `sugar` shell `jarabe`.

Part of the modal behaviour is the tracking of multiple modal dialogs at the same time.  Such as <kbd>alt</kbd>+<kbd>shift</kbd><kbd>m</kbd> which launches My Settings.  That's what `push_modal` and `pop_modal` do.

In removing the modal behaviour tracking from the toolkit in your commits here, you effectively remove the modal behaviour tracking from the dialog in the shell.

So can you either show a test case to demonstrate that modal behaviour tracking is not required, or move the calls into the shell?

I'm trying out the Journal project feature at the moment to try to make such a test case, but I've forgotten how it works and it doesn't seem to be working the way I remember.

**Comment by Pro-Panda** [comment]
Thank you for the detailed explanation. 

I tested using [Sugar Toolkit @58224cb](https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/58224cb15d84765e79492c7bb513e952e856cbfe) and [Sugar @489974f](https://github.com/sugarlabs/sugar/commit/489974f4243eb3a18c0bea07812c436ed8aa7d5c), and the behaviour of `ActivityChooser` is not modal. 

I am able to access other sections outside of the `PopWindow`. I'll try to make a patch in `jarabe` to fix the same, thanks

**Comment by Pro-Panda** [comment]
While I am now working on making a patch for `jarabe`, I think this can be merged since `ActivityChooser` was not modal before these changes

**Comment by Pro-Panda** [comment]
Noted, thanks

**Comment by pro-panda** [comment]
Closing. Relevant PR open at https://github.com/sugarlabs/sugar-toolkit-gtk3

**Pull request closed without merging**
