### PR TITLE
Added documentation and example for progressicon

### PR DESCRIPTION
**Pull request by Hrishi1999**
I have added docs and example for progressicon. 
Earlier PRs:
https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/354
https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/299

Review it.

### CODE REVIEW

**Comment by i5o** [comment]
Ran flake8 for the example; got
```
[ignacio@ignacio-laptop ~] $ flake8 progressicon.py 
progressicon.py:6:1: F401 'sugar3.graphics.icon.get_surface' imported but unused
progressicon.py:6:1: F401 'sugar3.graphics.icon.Icon' imported but unused
progressicon.py:54:1: E305 expected 2 blank lines after class or function definition, found 1
[ignacio@ignacio-laptop ~] $ 
```

**Comment by i5o** [comment]
You still have 2 commits, and looks like not full description of each one; you can squash them and just write a description
Please provide a brief description of what each commit adds (as usual);

**Comment by Hrishi1999** [comment]
@i5o flake8 Doesn't give any output.

**Comment by quozl** [comment]
which version?

**Comment by Hrishi1999** [comment]
I just used it via command line (Ubuntu 14.04)

**Comment by quozl** [comment]
Checked your 5cabf3f8b0450836080d84e780608af17792ea56 on two different systems;

## on Ubuntu 16.04

```
# flake8 examples/progressicon.py 
examples/progressicon.py:6:1: F401 'Icon' imported but unused
examples/progressicon.py:6:1: F401 'get_surface' imported but unused
```

## on Ubuntu 14.04
# flake8 examples/progressicon.py 
examples/progressicon.py:6:1: F401 'Icon' imported but unused
examples/progressicon.py:6:1: F401 'get_surface' imported but unused
examples/progressicon.py:24:7: E121 continuation line indentation is not a multiple of four
examples/progressicon.py:25:7: E121 continuation line indentation is not a multiple of four
examples/progressicon.py:26:7: E121 continuation line indentation is not a multiple of four
examples/progressicon.py:27:7: E121 continuation line indentation is not a multiple of four
```

Check the command you used or the flake8 package versions.  Ubuntu 14.04 has python-flake8 2.1.0-1ubuntu1 and Ubuntu 16.04 has python-flake8 2.5.4-2

**Comment by quozl** [comment]
Reviewed.  I don't consider the `flake8` failings important, but if @i5o wants them fixed, you'd better fix them.

**Comment by Hrishi1999** [comment]
@i5o Should I really do what you said. According to @quozl , radiotoolbutton.py fails flake8 too!

**Comment by i5o** [comment]
I'll do it after merging

**Comment by Hrishi1999** [comment]
@i5o, should I stop working on this PR then? I mean is it ready for merging?

**Comment by i5o** [comment]
:) thanks, good job.

**Comment by Hrishi1999** [comment]
@i5o Welcome :)

**Pull request merged**
