### PR TITLE
Change make-doc.sh interpreter

### PR DESCRIPTION
**Pull request by ndefilippis**
Changing interpreter to /bin/sh from /usr/bin/sh so it will work with ubuntu

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed.  Affects Ubuntu.  Does not affect Fedora.

**Comment by samdroid-apps** [comment]
Please change the commit message to add a note that it effects ubuntu.

Please change the first line of the commit message to something more descriptive than the file name

**Comment by quozl** [comment]
@ndefilippis, you only changed the pull request title, you've yet to "git commit --amend" your patch and "git push --force" your patch-1 branch.

**Comment by quozl** [comment]
Erk, now we have three patches.  Time to rebase and force push please?

**Comment by quozl** [comment]
Hey, now we have five!  :grin:

**Comment by samdroid-apps** [comment]
Looks good

**Comment by quozl** [comment]
Reviewed.

**Pull request merged**
