### PR TITLE
Update progressicon.py

### PR DESCRIPTION
**Pull request by Hrishi1999**

### CODE REVIEW

**Comment by goutamnair7** [comment]
Looks good to me :+1: 
@samdroid-apps good to merge?

**Comment by Hrishi1999** [comment]
Thanks.

**Comment by quozl** [comment]
Reviewed.

**Comment by Hrishi1999** [comment]
Please review toogletoolbutton.py :D

**Comment by quozl** [comment]
Are you going to resubmit your progressicon.py changes?  They were not merged.

**Comment by Hrishi1999** [comment]
https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/354

**Pull request closed without merging**
