### PR TITLE
progresstoolbutton.py added in src/graphics/

### PR DESCRIPTION
**Pull request by iamutkarshtiwari**
@samdroid-apps This PR integrated this requested feature -> https://bugs.sugarlabs.org/ticket/4721
Cross reference to other required PR - https://github.com/sugarlabs/browse-activity/pull/24
desktop-animation

### CODE REVIEW

**Comment by quozl** [comment]
* added bug label, as it is for bug 4721,
* added feature label, since it adds a feature to the toolkit,
* reviewed.

**Comment by iamutkarshtiwari** [comment]
@quozl  indentation fixed! :)

**Comment by quozl** [comment]
You have a mix of spaces and tabs on the Makefile.am line, please change it to be consistent with the other lines in the file, then collapse (rebase) your patches and force push your branch.

**Comment by iamutkarshtiwari** [comment]
Inconsistencies removed.

**Comment by iamutkarshtiwari** [comment]
I think that I should rather add this file to the browse repository because it's only being used by the browse's webtoolbar. There is no use of adding a module to sugar-toolkit if it's only going to used by just one activity. @quozl What are your suggestions on this sir?

**Comment by quozl** [comment]
It is more likely to be used by other activities and Sugar if it is in the toolkit, and I think it is a useful addition to the toolkit, so my preference is that it should be merged for 0.110.  To effect that, leave this pull request open waiting for our maintainer.

Meanwhile, for Browse, so that the next release may be used on older versions of Sugar such as 0.108, you should try to import the class from the toolkit, and if that fails use a local class in the Browse source repository.

**Comment by quozl** [comment]
In testing, I've found that *set_tooltip*() must be called in order to update the progress on display.  In other words;

```python
    button.update(x)
    button.set_tooltip('something')
```

It would be better if the second call was not needed.  Have you any suggestions?

**Comment by iamutkarshtiwari** [comment]
Do you mean that the update() function is dependent on set_tooltip() or do you need an alternate option to display the progress?

**Comment by quozl** [comment]
update() seems to be dependent on set_tooltip(), in that the icon fill
does not change if only update() is called in a timeout callback.

At the same time, other timeout callbacks do cause updates.

Was discovered in development of the Clock activity pull request.

Workaround was to put extra set_tooltip() calls in.

**Comment by iamutkarshtiwari** [comment]
Looking into this.

**Comment by iamutkarshtiwari** [comment]
@quozl Try adding ```self.queue_draw()``` after ```242'nd line``` in the ```update()``` function. I think this should fix the problem. Let me know if it works, I'll update the patch.

**Comment by quozl** [comment]
@iamutkarshtiwari, thanks, that fixes it.

For the record, https://github.com/godiard/clock-activity/pull/2 is the pull request related to my question.

**Comment by samdroid-apps** [comment]
Awsome.  This is like the widget that we need.  If you're looking for more places to use it, maybe look at the file transfer notifications in sugar shell (to show download progress).

Vauge comments:

* API Docs are great.  Please do them.  See an example of the format with this patch:  https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/269/files
* Can I make this pulse as well?  With a progress bar, I would use the pulse to indicate that progress is being made, however I do not know any numbers.
* You duplicated lots of the methods of the class (eg. get_accelerator, do_clicked, ...), as well as some auxiliary functions (_add_accelerator, etc.) from the toolbutton.py file.  Can you import them and make the ProgressToolButton a subclass to inherent those methods?  Duplication is bad

Specific comments:

[https://gyazo.com/32bd9ad367023faef413f96c3139c89d](https://gyazo.com/32bd9ad367023faef413f96c3139c89d)

* Normal toolbuttons have a black background when the palette is down.  This is done through adding the "toolbutton" and palette-down css classes (just search for that in the toolbutton file).  Please add that feature.
* The sizing seems a little off, see the screenshot above.  That was tested when SUGAR_SCALING=100 (as in the environment variable)
* Please make the orientation value come from constants rather than random strings.  Eg. Gtk.Orientation.VERTICAL not 'verticacl'.  It is eaiser to see typos that way (AttributeError vs nothing)

Otherwise, this is amazing.

**Comment by iamutkarshtiwari** [comment]
@samdroid-apps Updated and rebased commits.

Following defects are fixed->

- Documented the functions and the class.
- Functions duplication removed(apologies for that mistake). Inheritance implemented.
- Palette's background fixed.
- Orientation value now comes from constant (Gtk.Orientation.VERTICAL)

- The sizing of the download icon is initialized in ```webtoolbar.py to -> style.STANDARD_ICON_SIZE``` . It's pretty weird why it's appearing like that. I need to take a closer look but this shouldn't cause much issue.

**Comment by quozl** [comment]
Tested on Fedora 18 with https://github.com/sugarlabs/browse-activity/pull/24.

Confirmed that background is black, and sizing looks right on an XO laptop.

**Comment by iamutkarshtiwari** [comment]
@samdroid-apps I think it's good to go now..?

**Comment by i5o** [comment]
wow!

I will test, but I think @samdroid-apps have the final decission

**Comment by samdroid-apps** [comment]
This is good, but we are refactoring this to work better.  See the https://github.com/sugarlabs/browse-activity/pull/24 patch for the discussion.  I'll close this pull request until we work that out.

**Pull request closed without merging**
