### PR TITLE
Port from GObject to GLib

### PR DESCRIPTION
**Pull request by Pro-Panda**

### CODE REVIEW

**Comment by quozl** [comment]
Several new E127 and E501.

**Comment by Pro-Panda** [comment]
Made several PEP8 style changes and flake fixes using `autopep8`. Please re review

**Comment by quozl** [comment]
Again, my preference is not to autopep8, as now the change is way larger than is practical to review without losing attentiveness to the purpose of the pull request.  It also breaks the use of flake8 comparison as a review step.

**Comment by Pro-Panda** [comment]
Removed `autopep8` changes. Made flake8 fixes. 
Please re-review, thanks

**Pull request merged**
