### PR TITLE
Add weblate sync workflow

### PR DESCRIPTION
**Pull request by chimosky**
This will automatically open a PR whenever weblate pushes changes to weblate-sync.

### CODE REVIEW

**Comment by quozl** [comment]
File name has syc instead of sync?

Is anyone looking after the CI/CD checks, or should we really disable them because they don't have a champion?

**Comment by chimosky** [comment]
> File name has syc instead of sync?
> 
> Is anyone looking after the CI/CD checks, or should we really disable them because they don't have a champion?

Fixed the filename, I'll look at the error with building the doc.

**Comment by chimosky** [comment]
@quozl we should merge this as it has nothing to do with the documentation workflow that's failing, I looked into it before and just started looking at it again.

**Comment by quozl** [comment]
I'm okay for you to merge this.  I would do it myself but I'm not confident I know enough to support it.

**Pull request merged**
