### PR TITLE
Get audio and video mimes from GStreamer, fixes #3826

### PR DESCRIPTION
**Pull request by samdroid-apps**
Replaces #190

This uses multiprocessing to do the computation in the background.  (Not multithreading because of the GIL...)

### CODE REVIEW

**Comment by SAMdroid-apps** [comment]
Requires https://github.com/sugarlabs/sugar/pull/472

**Comment by SAMdroid-apps** [comment]
Just force pushed @godiard, now passes flake 8

**Comment by quozl** [comment]
@godiard, this is first use of "import multiprocessing".  Would it be better to implement using subprocess.Popen and GLib.source_add_*?

**Comment by SAMdroid-apps** [comment]
@quozl Let's try to not make the whole code more complex than it should be.  Multiprocessing is simple and pythonic and does the job fine.  It works in contexts where there is no GSomething main loop.

**Comment by quozl** [comment]
Is this called where there is no main loop?

**Comment by SAMdroid-apps** [comment]
It could be... mimes may be used for scripts and stuff

**Comment by quozl** [comment]
Yes, it could be, everything could be ... but is it actually called by anything that isn't using an event main loop?  That is to say, is there a hard requirement for the code to avoid dependency on the event main loop?

**Comment by SAMdroid-apps** [comment]
@quozl Are you ok with this patch?  We need to make a decision today as the feature freeze is today (in oz time anyway)!

**Comment by SAMdroid-apps** [comment]
Other freeze sorry, the feature freeze is way past

**Comment by quozl** [comment]
Testing on XO-1, standby.

**Pull request closed without merging**
