### PR TITLE
Tick based animation

### PR DESCRIPTION
**Pull request by samdroid-apps**
Gtk 3.8 introduces the tick callback [1].  This allows widgets to be
signaled before each frame, simmilar to requestAnimationFrame in the
browser.

This patch adds an optional widget argument to the Animator class so
tick based animation can be used.  This is much more efficent than
using timeouts, as we get a more appropriate frame rate for the user.

[1] https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-add-tick-callback

### CODE REVIEW

**Comment by godiard** [comment]
@samdroid-apps, could you explain what test you did and what are the results?
Would be good have more information. Also, we need test, specially with old hardware like 
the XO-1

**Comment by samdroid-apps** [comment]
To test, just observe how much more fps the animations are!  They should look silky smooth on recent (eg. 2007 laptop) hardware.

On slower devices (eg. XO4) the change is less visible, because it is based on the devices performance at an given time.

On even slower devices (eg. XO1) they may be less fps, but less fps is way we seem to want on XO1... I can't test though. (CC @quozl)

BTW:  the tick events are introduced in Fedora 19 - so there will be no change on f18 based builds

**Comment by quozl** [comment]
Happy to test, but I need a test plan.  It isn't clear what I have to do to test it.  As this involves another pull request, I'd hope that a ticket at bugs.sugarlabs.org might be the best place to organise this.

**Comment by samdroid-apps** [comment]
Feature page:  http://wiki.sugarlabs.org/go/Features/Tick_based_animation

**Comment by samdroid-apps** [comment]
I will rebase this and retest this

**Pull request closed without merging**
