### PR TITLE
Fix GtkMenu palette positioning in Gtk 3.16

### PR DESCRIPTION
**Pull request by samdroid-apps**
It fixes it most of the time :smile:

Still no progress on the anti-seizure front.

### CODE REVIEW

**Comment by godiard** [comment]
@samdroid-apps, I am worried of merge this change without be able to test does not break in other environments :/

There are a error message? What changed in data?

**Comment by samdroid-apps** [comment]
@godiard There is a trace back without the patch, because there are too many arguments.

It appears to be that the x and y arguments have changed from "out" arguments [1] to "inout" arguments [2].  This probably means that gir is passing the arguments to the functions now.

We don't need the new arguments and we never needed the user data argument, so we can just use the `*` to dump whatever arguments we get in the data list and forget about them!  This patch will not break compatibility.

[1]  https://developer.gnome.org/gtk3/3.14/GtkMenu.html#GtkMenuPositionFunc
[2]  https://developer.gnome.org/gtk3/stable/GtkMenu.html#GtkMenuPositionFunc

**Comment by samdroid-apps** [comment]
Could we merge this patch before the release?

Otherwise the clipboard palette will be super stuffed up in Fedora 23.

It will not break other environments, see the comment above.

**Comment by godiard** [comment]
Merged. It's low risk and fixes a error.
Would be good if commit header was more explicit bot what is solving,
right now, is not a good registry for the future. (This https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/221#issuecomment-106940548 is a good example of the information that would be nice have in the header)

**Pull request closed without merging**
